//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRPD_WebApp.db
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;

    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            byte[] b = new byte[16];
            RandomNumberGenerator.Create().GetBytes(b);
            Keynum = Convert.ToBase64String(b);
            Visited = DateTime.UtcNow;
            this.IsConfirmed = false;
        }
    
        public int Id { get; set; }
        public string Keynum { get; set; }
        public System.DateTime Visited { get; set; }
        public bool IsConfirmed { get; set; }
    }
}
