//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNetWebApp.db
{
    using System;
    using System.Collections.Generic;

    public partial class Guest
    {
        
        public int Id { get; set; }
        public byte[] Keynum { get; set; }
        public System.DateTime Visited { get; set; }
        public bool IsConfirmed { get; set; }
    }
}



