//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueNetWebApp.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int regID { get; set; }
        public string deviceID { get; set; }
        public string userName { get; set; }
    }
}
